project_id = "nalkwmxirqrniasohagh"

[functions.createRun]
verify_jwt = false

[functions.salvarResposta]
verify_jwt = false

[functions.finalizarDiagnostico]
verify_jwt = false

[functions.claimRun]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.updateComplementaryData]
verify_jwt = false
