version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - caddy_data:/data
     - caddy_config:/config
     - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
     - web
  lovable-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lovable-frontend
    ports:
      - "80:80" # Mapeia a porta 8080 do seu PC para a 80 do contêiner
    restart: always
    environment:
      # Variáveis de ambiente devem ser passadas aqui
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
volumes:
  caddy_data:
  caddy_config:
networks:
  web:
