version: "3.9"

services:
frontend:
    build: .
    ports:
     - "8080:80"
    depends_on:
     - db

db:
    image: supabase/postgres
    restart: always
    environment:
     POSTGRES_PASSWORD: 9-SB]6`M2"LaA%o8
    ports:
     - "5432:5432"
