version: "3.9"

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
      - internal

  lovable-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lovable-frontend
    restart: always
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
    networks:
      - internal

networks:
  internal:
    driver: bridge

  web:
    external: true
    name: web

volumes:
  caddy_data:
  caddy_config:
