// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nalkwmxirqrniasohagh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hbGt3bXhpcnFybmlhc29oYWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1Mzc1MTcsImV4cCI6MjA4NTExMzUxN30.BLb9HhffBUf_lg6vK1QjoErBaiT18FdyOlHan65wHEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});